# This is a basic workflow to help you get started with Actions
name: Fabric mod jar build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the fabric branch
on:
  push:
    branches: [ fabric ]
  pull_request:
    branches: [ fabric ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Set up the compiler
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Runs a single command using the runners shell
      - name: Build using gradle
        run: ./gradlew build
      
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
    
      - uses: actions/upload-artifact@v2
        with:
          name: KAMI mod jar
          path: '*/build/libs/kami-1.16.?.jar'
      
